# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Takenet
tagline:          'Takenet'
description:      'Onde o mundo de telefonia vira negócio para todos.<br>Sms Corporativo BH, mobile business, telefones celulares brasil, sms soluções'
url:              takenet.github.io
baseurl:          /

author:
  name:           'Take.net'
  url:            take.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/takenet/takenet.github.io
